name: company_blog
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19=hecd8cb5_1
  - certifi=2020.12.5=py39hecd8cb5_0
  - click=7.1.2=pyhd3eb1b0_0
  - email-validator=1.1.2=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - flask-login=0.5.0=py_0
  - flask-sqlalchemy=2.4.4=py_0
  - flask-wtf=0.14.3=py_0
  - freetype=2.10.4=ha233b18_0
  - idna=3.1=pyhd3eb1b0_0
  - itsdangerous=1.1.0=pyhd3eb1b0_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jpeg=9b=he5867d9_2
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.2.0=h9da4c3f_0
  - libwebp-base=1.2.0=h9ed2024_0
  - lz4-c=1.9.3=h23ab428_0
  - markupsafe=1.1.1=py39h9ed2024_0
  - ncurses=6.2=h0a44026_1
  - olefile=0.46=py_0
  - openssl=1.1.1j=h9ed2024_0
  - pillow=8.1.2=py39h5270095_0
  - pip=21.0.1=py39hecd8cb5_0
  - python=3.9.2=h88f2d9e_0
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - sqlalchemy=1.3.23=py39h9ed2024_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - tzdata=2020f=h52ac0ba_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wtforms=2.3.3=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - alembic==1.5.7
    - dnspython==2.1.0
    - flask-migrate==2.7.0
    - is-disposable-email==1.0.0
    - mako==1.1.4
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - six==1.15.0
    - wtforms-validators==1.0.0
prefix: /Users/peterhaas/opt/anaconda3/envs/company_blog
